name        : font-clear-sans-ttf
version     : 1.00
release     : 4
source      :
    - https://01.org/sites/default/files/downloads/clear-sans/clearsans-1.00.zip : 41809a296870dd7b4753d6532b4093821d61f9806281e6c053ccb11083ad1190
license     : Apache-2.0
component   : desktop.font
summary     : Clear Sans Fonts - TrueType
description : |
    Adopted by Mozilla for the Firefox for Android browser, Clear Sans has been recognized as a versatile OpenType font for screen, print, and Web. Clear Sans was designed with on-screen legibility in mind. It strikes a balance between contemporary, professional, and stylish expression and thoroughly functional purpose. It has a sophisticated and elegant personality at all sizes, and its thoughtful design becomes even more evident at the thin weight.
install    : |
    install -dm00644 $installdir/usr/share/fonts/truetype/clear-sans/
    install -Dm00644 TTF/*.ttf $installdir/usr/share/fonts/truetype/clear-sans/
    install -Dm00644 $pkgfiles/metainfo.xml $installdir/usr/share/appdata/font-clear-sans-ttf.metainfo.xml
